### ISSUE TITLE
Chapter 22 Homework

### ISSUE THREAD

**Issue by BawCOS** [DS-USAFA/Computational-Probability-and-Statistics#19]
Part d of homework 2 in chapter 22 asks for a bootstrap. We have not done bootstrap yet. This was the shuffling of chapters over the summer.
 -------
Create a bootstrap distribution of the differences in sample standard deviations, and report a 95% confidence interval. Compare with part c.

**Comment by bdhitt** [comment]
Removed from solutions manual.
